stages:
  - test
  - deploy

variables:
  AWS_ACCOUNT_NUMBER: "sdasdadad"
  AWS_REGION: "eu-central-1"
  ENVIRONMENT: "stage"
  NAMESPACE: "default"

test_stack:
  stage: test
  variables:
    NAMESPACE: "test"
  script:
    - kubectl create namespace test || true
    - kubectl apply -f elasticstack/elasticsearch.yml --namespace=${NAMESPACE}
    - kubectl apply -f elasticstack/kibana.yml --namespace=${NAMESPACE}
    - kubectl apply -f elasticstack/filebeat-configmap.yml --namespace=${NAMESPACE}
    - kubectl apply -f elasticstack/filebeat-daemonset.yml --namespace=${NAMESPACE}

deploy_stack:
  when: manual
  variables:
    NAMESPACE: "live"
  stage: deploy
  script: "echo 'This is the deploy stage'"

