apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - "*"
